name: newnippon
description: Android App for doing Shopping Online.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3 # iOS icons
  razorpay_flutter: ^1.2.2 # RazorPay Payment Gateway
  google_sign_in: ^4.5.1 # Google Sign in
  firebase_core: ^0.4.0+9 # Firebase plugin
  cloud_firestore: ^0.13.7 # Firebase Database Service
  firebase_auth: ^0.14.0+5 # Firbase Authentication Service
  shared_preferences: ^0.5.8 
  carousel_slider:
  font_awesome_flutter: ^8.8.1 # Font-Awesome icons
  flutter_svg: ^0.18.0 
  google_fonts: ^1.1.0
  flutter_phoenix: ^0.1.0
  fluttertoast: ^7.0.2 # Native Toast Plugin
  intl: ^0.16.1
  cached_network_image: ^2.2.0+1 # To cache Network Images 
  flutter_slidable: ^0.5.5
  dynamic_theme: ^1.0.1 # Dark Mode
  sqflite: # Native SQlite Database
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/shopper.svg
    - images/laptop1.jpg
    - images/laptop2.jpg
    - images/laptop3.jpg
    - images/mobile1.jpg
    - images/mobile2.jpg
    - images/mobile3.jpg
    - images/empty-cart.png
    - images/order.svg
    - images/Success_payment.png
    - images/empty-search.png


  fonts:
    - family: KaushanScript
      fonts:
        - asset: fonts/KaushanScript-Regular.ttf
    - family: MeriendaOne
      fonts:
        - asset: fonts/MeriendaOne-Regular.ttf
