name: newnippon
description: Android App for doing Shopping Online.
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  razorpay_flutter: any # RazorPay Payment Gateway
  firebase_core: ^1.0.3 # Firebase plugin
  cloud_firestore: ^1.0.4 # Firebase Database Service
  firebase_auth: ^1.0.3 # Firbase Authentication Service
  shared_preferences: any 
  carousel_slider: ^3.0.0
  font_awesome_flutter: any # Font-Awesome icons
  google_fonts: any
  salomon_bottom_bar: ^3.0.0
  flutter_phoenix: any
  fluttertoast: any # Native Toast Plugin
  intl: any
  cached_network_image: any # To cache Network Images 
  flutter_slidable: any
  dynamic_themes: ^1.1.0
  sqflite: # Native SQlite Database
  path:
  flutter_svg: ^0.21.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/shopper.svg
    - images/laptop1.jpg
    - images/laptop2.jpg
    - images/laptop3.jpg
    - images/mobile1.jpg
    - images/mobile2.jpg
    - images/mobile3.jpg
    - images/empty-cart.png
    - images/order.svg
    - images/Success_payment.png
    - images/empty-search.png


  fonts:
    - family: KaushanScript
      fonts:
        - asset: fonts/KaushanScript-Regular.ttf
    - family: Whitney
      fonts:
        - asset: fonts/Whitney-Book.otf